name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'aiidalab/aiidalab-qe-pp'
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install flit
        run: pip install flit~=3.4
      - name: Build and publish
        run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      - uses: softprops/action-gh-release@v2
        name: Create release
        with:
            files: |
              dist/*
            generate_release_notes: true
